version: "3.9"

services:
    web:
        image: docker/compose

    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379

    backendserver:
        build: .
        command: ./docker-init.sh
        restart: unless-stopped
        volumes:
            - .:/src
        ports:
            - 5000:5000
        env_file: .env
        depends_on:
            - redis

volumes:
    urlshortenerdb:
        external: false
